### ISSUE TITLE
Availability backbone model

### ISSUE THREAD

**Issue by danielcanueto** [lesscomfortable/SpanishULMFit#1]
Hi!

Thanks for your effort, seems very promising.

However, I got stuck with getting the backbone model in "Load Encoder Weights for Language Model" section. How could I get this backbone model?

in addition, a couple suggestions for reproducibility of notebook:

The spacy model for Spanish needs to be downloaded: 

!python -m spacy download es

And a link to the dataset would be cool:

http://www.sepln.org/workshops/tass/tass_data/download.php?auth=ntcabsQs44XedvseKre

I'm trying to replicate in Google Colab your work, right now available here:

https://github.com/danielcanueto/misc/blob/master/Spanish_GeneralTASSv2.ipynb

When this Colab is finished; i'll let you know and cite you as the responsible of this work.

Thanks!

Daniel

**Comment by fpingham** [comment]
Hey Daniel. I have the model but it is too heavy for Github, how would you rather I send it to you? Would you like to share an open GDrive where I can upload it?

Thanks in advance,
Francisco

**Comment by danielcanueto** [comment]
Hi Francisco,

Sure, give me an e-mail address and I'll share a link to edit the Google Drive folder so you can upload the file there:

https://www.gtricks.com/drive/upload-files-someone-elses-google-drive/

I have right now 10 GB available.

Thanks a lot!

Daniel

**Comment by nicalvarez** [comment]
Hi to both of you,
I am also interested in having access to the model. 
@danielcanueto could you share the GDrive link once the model is uploaded?

Thanks for your work

**Comment by danielcanueto** [comment]
Sure, no problem, if @lesscomfortable agrees with it.

**Comment by fpingham** [comment]
Absolutely. The more the merrier.

**Comment by danielcanueto** [comment]
Here there is the link with the access to the model: 

https://drive.google.com/drive/folders/1D6w8N6iooaQEMWFVKsm8V-Yf4hH_kovk?usp=sharing

Thanks a lot Francisco! Very very busy these days finishing my PhD, but I hope to reproduce its use during next days.

**Comment by fpingham** [comment]
It would be cool to update this repository with the lastest techniques in NLP applied to Spanish. For starters check [Improving Language Understanding with Unsupervised Learning](https://blog.openai.com/language-unsupervised/) and [ELMO](https://allennlp.org/elmo)

**Comment by nicalvarez** [comment]
This [repo ](https://github.com/IndicoDataSolutions/finetune) provides an implementation of the OpenAI model (pretrained on English only).

But in this [issue](https://github.com/IndicoDataSolutions/finetune/issues/56) they discuss modifications needed to train for other languages.

**Comment by fpingham** [comment]
Yeah, we could use that as a guide. Is anyone interested in collaborating?

**Comment by fpingham** [comment]
@danielcanueto Daniel, would you care if I shared these weights openly in the repo's README?

**Comment by danielcanueto** [comment]
No problem.

In my case, I'm finishing this month my PhD thesis while working and trying to finish two manuscripts, so you might guess I'm right now overloaded. :D After September 2nd, I should have much more time to help in whichever necessary.

**Comment by samhavens** [comment]
👋 Hi @lesscomfortable and @danielcanueto. Just to confirm: The model linked to on GDrive the pretrained backbone model, analogous to the English one used in the Fastai IMDB notebook?

It doesn't look like the code for generating that model is in this repo though. Is that code in a repo anywhere? I might be interested in hosting some of these pretrained models for various languages.

**Comment by samhavens** [comment]
Maybe I am confused, but in addition to 'lm1_weights_kl.h5', don't we also need 'itos+100.pkl', the int to string mapping from the run that generated the base model?

**Comment by fpingham** [comment]
Hi Sam, with respect to the code for generating the model, the general code is in fact in the repo (Wiki_Corpus.ipynb) but the actual code used for that model used different hyperparameters. Those weights were obtained by a fellow student with whom I was experimenting and he did not send me his notebook, only the hyperparemeters. He used the weights from the Wiki_Corpus.ipynb as initial weights and he changed some hyperparameters for training. I'll see if I can get the original notebook, in the meantime here are the changes he made when he re-trained:

drops = np.array([0.25, 0.1, 0.2, 0.02, 0.15])*0.4
learner.clip=.4
learner.fit(lr, 1.5, cycle_len=5, use_clr_beta=(10,10,0.95,0.85), best_save_name="spanish-best-1")

**Comment by fpingham** [comment]
I uploaded the itos file to the GDrive folder. By the way, what is your plan? I was thinking on replicating the fast.ai post in a Github repo so it has more accessibility, does this conflict with your plan?

**Comment by samhavens** [comment]
Thanks @lesscomfortable for uploading the `itos` map! I'm partly done with my own run now, so (assuming it works) I will compare the two. I am using an AWS c5.18xlarge, so am hoping to get by without removing tokens (except when they are below the threshold frequency), so it might give better results...

Since we are planning on build base language models for a few languages, I thought I could host them and their corresponding `itos` maps on S3... but then I saw that Jeremy Howard is planning on doing that at nlp.fast.ai.
